name: Generate Python Client and Create PR

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-proto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Disable token persistence for security
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install git
        run: sudo apt-get install git

      - name: Run generation script
        run: ./generate_python_grpc_client.sh # Assuming your script is saved as generate_grpc.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This will allow access to create PR

      - name: Check for changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b generated-client
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Generated Python client from proto files"
            git push origin generated-client
          else
            echo "No changes detected."
            exit 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated-client
          title: "Generated Python client from proto files"
          body: "This PR contains the generated Python client from the proto files."
          labels: "auto-generated"
